### PR TITLE
Port to Qt 5

### PR DESCRIPTION
**Pull request by pzorin**
I see that you have implemented initial support for Qt5 while trying to keep compatibility with Qt4.
However, Qt4 has been unsupported upstream for a long time and also Debian plans to stop supporting it:
https://lists.debian.org/debian-devel-announce/2017/08/msg00006.html
Therefore I propose to abandon Qt4 support immediately.

### CODE REVIEW

**Comment by gocarlos** [comment]
Remove qt4 would be great. 

I’d eventually retarget the PR to the new branch in this repo (new/pyqt5) and then merge to master? 

Other than that, i also removed qt4 and python 2 here: https://github.com/gocarlos/krop 
Maybe you what to compare.

**Comment by pzorin** [comment]
@gocarlos: could you rebase your work onto the original author's repository? This would make it more discoverable and easier to integrate.

**Comment by arminstraub** [comment]
Just saw your comments now!  (I'm new to GitHub.)  I agree with eventually removing Qt4 but I don't want to do it just yet: the simplifications of the codebase are rather minimal and I would like for krop to work without issues on Ubuntu 14.04 LTS while that is officially supported (early 2019, I think).

**Comment by edumco** [comment]
Any changes about this port to QT5 ?

**Comment by arminstraub** [comment]
krop continues to work fine with both Qt4 and Qt5 (it had already been ported; the pull request here was suggesting to remove support for Qt4).  Since it has caused no extra effort to continue supporting Qt4 (and because I still have an old machine in use), the 0.6.0 release from a few days ago should run just as well on old systems (like Ubuntu 14.04) as on new systems (like Ubuntu 20.04).

**Pull request closed without merging**
